apiVersion: v1
kind: Service
metadata:
  name: movie-sent-service
    
spec:
  selector:
    app: movie-sent
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-sent
spec:
  selector:
    matchLabels:
      app: movie-sent
  replicas: 2
  template:
    metadata:
      labels:
        app: movie-sent
    spec:
      containers:
      - name: movie-sent
        image: YOUR_DOCKERHUB_USERNAME/movie-sent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
